steps:
  - checkout: self

  - task: CopyFiles@2
    displayName: Create project folder
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        logic/host.json
        logic/connections.json
        logic/parameters.portal.json
        logic/Artifacts/**/*
        logic/Order*/**
      TargetFolder: 'publish_output'   

  - task: CmdLine@2
    displayName: 'Rename logic apps params files'
    inputs:
      script: ren $(System.DefaultWorkingDirectory)\publish_output\logic\parameters.portal.json parameters.json

  - task: ArchiveFiles@2
    displayName: "Create project zip"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output/logic"
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    displayName: Create logic app artifact
    artifact: drop

  - publish: $(Build.Repository.LocalPath)/iac
    displayName: Create ARM template artifacts
    artifact: deploy