variables:
  - name: environmentName
    value: dev 
  - name: location
    value: uk south
  - name: locationName
    value: uksouth
  - name: shortLocation
    value: uks
  - name: storageUniqueId
    value: 4olw3zfflre3s    
  - name: sgType
    value: Standard_LRS